services:
  mysql:
    image: mysql:8.0
    container_name: wayforpay-givewp-test-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wayforpay_givewp_test
    ports:
      - "3307:3306"
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
